export const manualPortfolioEntries = [
  {
    id: 'portfolio__jsave',
    type: 'portfolio',
    slug: 'jsave',
    title: 'JSave',
    titleZh: 'J省',
    description: 'Personal finance PWA — track savings, spending, and daily item costs. Offline-first with auto salary.',
    descriptionZh: '个人财务 PWA — 记录收支、储蓄和物品日均成本。支持离线使用与自动发薪。',
    visible: true,
    order: -119,
    url: 'https://jsave.jeeprod.com',
    iconUrl: 'https://jsave.jeeprod.com/icons/icon-192.png',
  },
  {
    id: 'portfolio__mall',
    type: 'portfolio',
    slug: 'mall',
    title: 'JeeProd Mall',
    titleZh: 'JeeProd 商城',
    description: 'A curated e-commerce PWA — handpicked products, WhatsApp ordering, and real-time order tracking.',
    descriptionZh: '精品电商 PWA — 精心挑选的好物、WhatsApp 下单、实时追踪订单。',
    visible: true,
    order: -118,
    iconUrl: '/logo.svg',
    internalPath: '/mall',
  },
  {
    id: 'portfolio__matetrip',
    type: 'portfolio',
    slug: 'matetrip',
    title: 'MateTrip',
    titleZh: '伴旅',
    description: 'A collaborative trip planner for shared expenses, gallery moments, itineraries, and travel chat.',
    descriptionZh: '一个给多人旅行使用的协作工具，整合分账、相册、行程和旅途聊天。',
    visible: true,
    order: -120,
    url: 'https://matetrip.jeeprod.com',
    iconUrl: 'https://matetrip.jeeprod.com/icons/icon-192.png',
  },
  {
    id: 'portfolio__calculator',
    type: 'portfolio',
    slug: 'calculator',
    title: 'Calculator',
    titleZh: '计算机',
    description: 'A built-in calculator page inside Jee Production.',
    descriptionZh: '一个内建在 Jee Production 里的计算机页面。',
    visible: true,
    order: -100,
    iconUrl: '',
    internalPath: '/calculator',
  },
  {
    id: 'portfolio__unserialize',
    type: 'portfolio',
    slug: 'unserialize',
    title: 'Unserialize',
    titleZh: '反序列化工具',
    description: 'Convert between JSON and PHP serialize formats with quick copy tools.',
    descriptionZh: '在 JSON 和 PHP serialize 格式之间快速转换，并支持一键复制。',
    visible: true,
    order: -90,
    iconUrl: '',
    internalPath: '/unserialize',
  },
  {
    id: 'portfolio__lucky-calc',
    type: 'portfolio',
    slug: 'lucky-calc',
    title: 'Lucky Calc',
    titleZh: '幸运计算器',
    description: 'A multi-tool calculator: standard calc, 4D lucky numbers, 千字图 lookup, Niu Niu scorer, 4D payout, and interest calculator.',
    descriptionZh: '多功能计算器：计算机、4D幸运号、千字图查询、牛牛算分、4D赔率、利息计算。',
    visible: true,
    order: -110,
    iconUrl: '',
    internalPath: '/lucky-calc',
  },
  {
    id: 'portfolio__h-agency',
    type: 'portfolio',
    slug: 'h-agency',
    title: 'ℋ Agency',
    titleZh: '希望公会',
    description: 'Streamer recruitment platform for ℋ Agency — Hope Guild.',
    descriptionZh: '希望公会主播招募平台。',
    visible: true,
    order: -105,
    iconUrl: '',
    internalPath: '/h-agency',
  },
  {
    id: 'portfolio__flowchart',
    type: 'portfolio',
    slug: 'flowchart',
    title: 'FlowCraft',
    titleZh: 'FlowCraft',
    description: 'A drag-and-drop flowchart builder with node types, image annotations, and invite-based sharing.',
    descriptionZh: '拖拽式流程图工具，支持节点类型、图片注释与邀请码分享。',
    visible: true,
    order: -115,
    iconUrl: '',
    internalPath: '/flowchart',
  },
  {
    id: 'portfolio__matetrip-admin',
    type: 'portfolio',
    slug: 'matetrip-admin',
    title: 'MateTrip Admin',
    titleZh: 'MateTrip 管理台',
    description: 'Admin dashboard for managing MateTrip trips, users, receipts, and features.',
    descriptionZh: '管理 MateTrip 的旅程、用户、账单和功能开关。',
    visible: false,
    adminOnly: true,
    order: -130,
    iconUrl: '/matetrip-admin/icon-192.png',
    internalPath: '/matetrip-admin',
  },
]
