import { createContext, useContext, useState, useEffect } from 'react'

const translations = {
  en: {
    siteTitle: 'Jee Production',
    tagline: 'A place for future ideas, finished work, and useful links I want to keep close.',
    portfolio: 'Portfolio',
    bookmarks: 'Bookmarks',
    portfolioIntro: 'New ideas, works in progress, and experimental side projects — all live here.',
    bookmarkIntro: 'A small library of links worth keeping around and opening again.',
    about: 'About',
    aboutRole: 'Software Engineer',
    aboutLocation: 'Malaysia',
    aboutCurrent: 'ARMS Software International',
    aboutBio1: 'Software Engineer with a background spanning both hardware and software, focused on building web applications and full-stack solutions.',
    aboutBio2: 'Good at learning new things, able to quickly adapt to new environments. Enjoy building things that are both functional and well-crafted.',
    skills: 'Skills',
    portfolioEmpty: 'No portfolio entries yet.',
    bookmarkEmpty: 'No bookmarks yet.',
    entryFallback: 'A link worth keeping.',
    openLink: 'Open link',
    openApp: 'Open app',
    contactTitle: 'Get in touch',
    contactSubtitle: 'Have a project in mind or just want to say hello? Fill in the form or send an email directly.',
    contactName: 'Your name',
    contactEmail: 'Your email',
    contactMessage: 'Message',
    contactSend: 'Send message',
    contactSending: 'Sending...',
    contactSuccess: "Message sent — thanks! I'll get back to you soon.",
    contactError: 'Could not send. Try emailing directly at jeejunhong@gmail.com.',
    contactNamePh: 'Your name',
    contactEmailPh: 'you@example.com',
    contactMessagePh: 'Tell me about your project or idea...',
    opening: 'Opening',
    redirectIn: 'Redirect in',
    destination: 'Destination',
    externalSite: 'External site',
    openNow: 'Open now',
    notFound: 'This entry does not exist.',
    backHome: 'Back home',
    toggleLanguage: 'Toggle language',
    toggleTheme: 'Toggle theme',
    lightMode: 'Light',
    darkMode: 'Dark',
    login: 'Login',
    logout: 'Logout',
    close: 'Close',
    admin: 'Admin',
    adminTitle: 'Content Manager',
    adminLogin: 'Admin access',
    loginHint: 'Sign in to manage content on this site.',
    loginWithGoogle: 'Continue with Google',
    orContinueWith: 'or continue with email',
    register: 'Create account',
    registerHint: 'Join to save your own bookmarks and projects.',
    name: 'Display name',
    alreadyHaveAccount: 'Already have an account?',
    noAccount: "Don't have an account?",
    signIn: 'Sign in',
    email: 'Email',
    password: 'Password',
    loading: 'Loading...',
    add: 'Add',
    addEntry: 'New entry',
    editEntry: 'Edit entry',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    slug: 'Slug',
    entryType: 'Type',
    titleEn: 'Title (EN)',
    titleZh: 'Title (ZH)',
    descriptionEn: 'Description (EN)',
    descriptionZh: 'Description (ZH)',
    targetUrl: 'Target URL',
    iconUrl: 'Icon URL',
    order: 'Order',
    visibility: 'Visibility',
    visible: 'Visible',
    hidden: 'Hidden',
    success: 'Success',
    error: 'Error',
    saveSuccess: 'Saved successfully.',
    deleteSuccess: 'Deleted successfully.',
    deleteFailed: 'Delete failed.',
    calculatorTitle: 'Calculator',
    calculatorIntro: 'A small built-in utility page. Clean, fast, and easy to reach directly from the portfolio.',
    calculatorTips: 'Quick notes',
    calculatorPath: 'Route',
    route: 'Route',
    calculatorReady: 'Start typing',
    calculatorError: 'Error',
    unserializeTitle: 'Unserialize',
    unserializeIntro: 'Switch between JSON and PHP serialize, then serialize or unserialize with a single action.',
    toolFormat: 'Format',
    toolMode: 'Mode',
    toolHowItWorks: 'How it works',
    jsonSerializeHelp: 'Serialize will validate your JSON and output a compact JSON string.',
    jsonUnserializeHelp: 'Unserialize will validate your JSON and output a readable, pretty-printed version.',
    phpSerializeHelp: 'Serialize expects JSON input and converts it into PHP serialize format.',
    phpUnserializeHelp: 'Unserialize expects a PHP serialized string and converts it into formatted JSON.',
    toolInput: 'Input',
    toolOutput: 'Output',
    toolEditor: 'Editor',
    toolResult: 'Result',
    toolOutputPlaceholder: 'Your converted result will appear here.',
    serializeAction: 'Serialize',
    unserializeAction: 'Unserialize',
    copy: 'Copy',
    clear: 'Clear',
    copied: 'Copied',
    toolSuccess: 'Converted successfully.',
    toolError: 'Could not convert this value.',
    jsonSerializeError: 'JSON serialize failed.',
    jsonUnserializeError: 'JSON unserialize failed.',
    phpSerializeError: 'PHP serialize failed.',
    phpSerializeInputError: 'PHP serialize expects valid JSON input.',
    phpUnserializeError: 'PHP unserialize failed.',
    builtIn: 'Built-in',
    systemEntryHint: 'This is a built-in page. You can update its icon and copy, but its route stays fixed.',
    selectEntry: 'Select an entry to edit',
    adminHint: 'Only admin can create portfolio items and bookmarks. Everything shown on the homepage comes from here.',
    slugRequired: 'Slug is required.',
    titleRequired: 'Title is required.',
    urlRequired: 'Target URL is required.',
    saveFailed: 'Save failed.',
    confirmDelete: 'Delete this entry?',
    untitled: 'Untitled',
    emptySection: 'Nothing here yet.',
  },
  zh: {
    siteTitle: 'Jee Production',
    tagline: '这里用来放未来的新想法、已经完成的作品，还有我想长期收藏的实用链接。',
    portfolio: '作品集',
    bookmarks: '书签',
    portfolioIntro: '以后有新的点子、想做的作品、实验性质的小项目，都放在这里展示。',
    bookmarkIntro: '这里放我觉得有用、值得反复打开看的网址收藏。',
    about: '关于我',
    aboutRole: '软件工程师',
    aboutLocation: '马来西亚',
    aboutCurrent: 'ARMS Software International',
    aboutBio1: '横跨硬件与软件领域的软件工程师，专注于 Web 应用开发与全栈方案。',
    aboutBio2: '喜欢学新东西，能快速融入新环境。享受打造兼具功能性与美感的产品。',
    skills: '技术栈',
    portfolioEmpty: '还没有作品内容。',
    bookmarkEmpty: '还没有书签内容。',
    entryFallback: '一个值得保留的链接。',
    openLink: '打开链接',
    openApp: '打开应用',
    contactTitle: '联系我',
    contactSubtitle: '有项目想法，或者只是想打个招呼？填写下面的表单，或者直接发邮件给我。',
    contactName: '你的名字',
    contactEmail: '你的邮箱',
    contactMessage: '留言内容',
    contactSend: '发送消息',
    contactSending: '发送中...',
    contactSuccess: '消息已发送，感谢！我会尽快回复你。',
    contactError: '发送失败，可以直接发邮件至 jeejunhong@gmail.com。',
    contactNamePh: '你的名字',
    contactEmailPh: 'you@example.com',
    contactMessagePh: '告诉我你的项目或想法...',
    opening: '正在跳转',
    redirectIn: '跳转倒计时',
    destination: '目标站点',
    externalSite: '外部网站',
    openNow: '立即打开',
    notFound: '这个内容不存在。',
    backHome: '返回首页',
    toggleLanguage: '切换语言',
    toggleTheme: '切换主题',
    lightMode: '浅色',
    darkMode: '深色',
    login: '登录',
    logout: '退出',
    close: '关闭',
    admin: '管理',
    adminTitle: '内容管理',
    adminLogin: '管理员入口',
    loginHint: '登录后即可管理网站内容。',
    loginWithGoogle: '使用 Google 登录',
    orContinueWith: '或使用邮箱登录',
    register: '注册账号',
    registerHint: '注册后可以保存书签和作品。',
    name: '显示名称',
    alreadyHaveAccount: '已有账号？',
    noAccount: '还没有账号？',
    signIn: '登录',
    email: '邮箱',
    password: '密码',
    loading: '处理中...',
    add: '新增',
    addEntry: '新建内容',
    editEntry: '编辑内容',
    edit: '编辑',
    delete: '删除',
    save: '保存',
    cancel: '取消',
    slug: '短链接标识',
    entryType: '内容类型',
    titleEn: '英文标题',
    titleZh: '中文标题',
    descriptionEn: '英文简介',
    descriptionZh: '中文简介',
    targetUrl: '跳转地址',
    iconUrl: '图标网址',
    order: '排序',
    visibility: '显示状态',
    visible: '显示',
    hidden: '隐藏',
    success: '成功',
    error: '错误',
    saveSuccess: '保存成功。',
    deleteSuccess: '删除成功。',
    deleteFailed: '删除失败。',
    calculatorTitle: '计算机',
    calculatorIntro: '一个内建的小工具页面，干净、快速，也可以直接从作品集进入。',
    calculatorTips: '小提示',
    calculatorPath: '路径',
    route: '路由',
    calculatorReady: '开始输入',
    calculatorError: '错误',
    unserializeTitle: '反序列化工具',
    unserializeIntro: '在 JSON 和 PHP serialize 之间切换，并且可以一键进行序列化或反序列化。',
    toolFormat: '格式',
    toolMode: '模式',
    toolHowItWorks: '说明',
    jsonSerializeHelp: '序列化会校验你的 JSON，并输出压缩后的 JSON 字符串。',
    jsonUnserializeHelp: '反序列化会校验你的 JSON，并输出更易读的格式化结果。',
    phpSerializeHelp: '序列化模式下，输入 JSON，输出 PHP serialize 字符串。',
    phpUnserializeHelp: '反序列化模式下，输入 PHP serialize 字符串，输出格式化 JSON。',
    toolInput: '输入',
    toolOutput: '输出',
    toolEditor: '编辑区',
    toolResult: '结果',
    toolOutputPlaceholder: '转换结果会显示在这里。',
    serializeAction: '序列化',
    unserializeAction: '反序列化',
    copy: '复制',
    clear: '清空',
    copied: '已复制',
    toolSuccess: '转换成功。',
    toolError: '无法转换当前内容。',
    jsonSerializeError: 'JSON 序列化失败。',
    jsonUnserializeError: 'JSON 反序列化失败。',
    phpSerializeError: 'PHP serialize 序列化失败。',
    phpSerializeInputError: 'PHP serialize 模式需要填写有效的 JSON 输入。',
    phpUnserializeError: 'PHP serialize 反序列化失败。',
    builtIn: '内建',
    systemEntryHint: '这是站内内建页面。你可以修改图标和文案，但它的路由会保持固定。',
    selectEntry: '先选择一个内容进行编辑',
    adminHint: '只有管理员可以管理作品集和书签。首页展示的所有内容都来自这里。',
    slugRequired: '必须填写短链接标识。',
    titleRequired: '必须填写标题。',
    urlRequired: '必须填写跳转地址。',
    saveFailed: '保存失败。',
    confirmDelete: '确定删除这个内容吗？',
    untitled: '未命名',
    emptySection: '这里还没有内容。',
  },
}

const LangContext = createContext(null)

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'zh')
  const toggleLang = () => setLang((current) => (current === 'en' ? 'zh' : 'en'))
  const t = (key) => translations[lang][key] ?? key

  useEffect(() => {
    localStorage.setItem('lang', lang)
  }, [lang])

  return (
    <LangContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
