import { createContext, useContext, useState } from "react";

const zh = {
  // Nav
  photos:       "照片",
  overview:     "概览",
  dashboard:    "仪表盘",
  data:         "数据",
  trips:        "旅程",
  users:        "用户",
  receipts:     "账单",
  pushSubs:     "推送订阅",
  tools:        "工具",
  broadcast:    "广播通知",
  features:     "功能控制",
  adminConsole: "管理后台",
  signOut:      "退出登录",
  refresh:      "刷新",
  superAdmin:   "超级管理员",

  // Login
  signIn:       "登录",
  adminOnly:    "仅限管理员访问。",
  email:        "邮箱",
  password:     "密码",
  signingIn:    "登录中…",

  // Dashboard
  dashboardSub:     "MateTrip 平台概览",
  totalTrips:       "总旅程数",
  allTime:          "所有时间",
  registeredUsers:  "注册用户",
  registered:       "已注册",
  totalReceipts:    "账单总数",
  sampled:          "采样",
  activeDevices:    "活跃设备",
  recentTrips:      "最近旅程",
  total:            "条",
  recentUsers:      "最近用户",
  spendByCurrency:  "💰 各货币消费",
  tripSizeDist:     "👥 旅程人数分布",
  noReceiptData:    "暂无账单数据",
  members:          "成员",

  // Trips
  tripsSub:     "所有旅程记录",
  allTrips:     "🗺 全部旅程",
  shown:        "条",
  searchTrips:  "搜索旅程…",
  trip:         "旅程",
  destination:  "目的地",
  owner:        "房主",
  currency:     "货币",
  joinCode:     "邀请码",
  details:      "详情",
  noTrips:      "暂无旅程",

  // Users
  usersSub:     "已注册账号",
  allUsers:     "👤 全部用户",
  searchUsers:  "搜索用户…",
  user:         "用户",
  noUsers:      "暂无用户",

  // Receipts
  receiptsSub:     "所有旅程的账单记录",
  allReceipts:     "🧾 全部账单",
  searchReceipts:  "搜索账单或旅程…",
  receipt:         "账单",
  amount:          "金额",
  date:            "日期",
  tags:            "标签",
  map:             "地图",
  noReceipts:      "暂无账单",
  viewMap:         "查看",

  // Push
  pushSubsSub:  "活跃设备推送订阅",
  allPushSubs:  "🔔 全部订阅",
  docId:        "文档 ID",
  tripId:       "旅程 ID",
  userId:       "用户 ID",
  updated:      "更新时间",
  remove:       "删除",
  noPush:       "暂无推送订阅",
  confirmRemovePush: "确定删除此推送订阅？",
  pushRemoved:  "订阅已删除",

  // Broadcast
  broadcastSub:     "向用户发送推送通知",
  sendNotif:        "📢 发送通知",
  broadcastDesc:    "向旅程成员发送推送通知，适用于公告、维护通知或新功能提醒。",
  notifTitle:       "通知标题（可选）",
  defaultTitle:     "默认为 'MateTrip'",
  message:          "消息内容 *",
  messagePlaceholder: "输入消息内容…",
  targetTrip:       "目标旅程",
  allTripsTarget:   "全部旅程",
  subscribers:      "位订阅者将收到此通知",
  sendBtn:          "📢 发送通知",
  sending:          "发送中…",
  enterMessage:     "请输入消息内容",
  noSubscribers:    "未找到活跃订阅者",
  sentSuccess:      "已发送至",
  devices:          "台设备",
  tripsCount:       "个旅程",

  // Trip Modal
  tripInfo:     "旅程信息",
  tripIdLabel:  "旅程 ID",
  joinCodeLabel:"邀请码",
  startDate:    "开始日期",
  endDate:      "结束日期",
  totalMembers: "总成员数",
  totalSpend:   "总消费",
  activity:     "活动统计",
  schedule:     "日程",
  messages:     "消息",
  photos:       "照片",
  people:       "旅伴",
  membersSection: "成员",
  deleteTrip:   "🗑 删除旅程",
  confirmDeleteTrip: "删除此旅程及所有数据？\n此操作无法撤销。",
  tripDeleted:  "旅程已删除",
  close:        "关闭",
  loadingDetails: "加载中…",

  // User Modal
  accountInfo:  "账号信息",
  uid:          "UID",
  username:     "用户名",
  displayName:  "显示名称",
  owned:        "拥有旅程",
  tripsLabel:   "参与旅程",
};

const en = {
  overview:     "Overview",
  dashboard:    "Dashboard",
  data:         "Data",
  trips:        "Trips",
  users:        "Users",
  receipts:     "Receipts",
  pushSubs:     "Push Subs",
  tools:        "Tools",
  broadcast:    "Broadcast",
  features:     "Features",
  adminConsole: "Admin Console",
  signOut:      "Sign out",
  refresh:      "Refresh",
  superAdmin:   "Super Admin",

  signIn:       "Sign In",
  adminOnly:    "Admin access only.",
  email:        "Email",
  password:     "Password",
  signingIn:    "Signing in…",

  dashboardSub:     "MateTrip platform overview",
  totalTrips:       "Total Trips",
  allTime:          "All time",
  registeredUsers:  "Registered Users",
  registered:       "Registered",
  totalReceipts:    "Total Receipts",
  sampled:          "Sampled",
  activeDevices:    "Active Devices",
  recentTrips:      "Recent Trips",
  total:            "total",
  recentUsers:      "Recent Users",
  spendByCurrency:  "💰 Spend by Currency",
  tripSizeDist:     "👥 Trip Size Distribution",
  noReceiptData:    "No receipt data yet",
  members:          "Members",

  tripsSub:     "All trip records",
  allTrips:     "🗺 All Trips",
  shown:        "shown",
  searchTrips:  "Name, destination, code…",
  trip:         "Trip",
  destination:  "Destination",
  owner:        "Owner",
  currency:     "Currency",
  joinCode:     "Join Code",
  details:      "Details",
  noTrips:      "No trips yet",

  usersSub:     "Registered accounts",
  allUsers:     "👤 All Users",
  searchUsers:  "Name, username, email…",
  user:         "User",
  noUsers:      "No users yet",

  receiptsSub:     "All expense records across trips",
  allReceipts:     "🧾 All Receipts",
  searchReceipts:  "Receipt or trip name…",
  receipt:         "Receipt",
  amount:          "Amount",
  date:            "Date",
  tags:            "Tags",
  map:             "Map",
  noReceipts:      "No receipts found",
  viewMap:         "View",

  pushSubsSub:  "Active device push subscriptions",
  allPushSubs:  "🔔 All Subscriptions",
  docId:        "Document ID",
  tripId:       "Trip ID",
  userId:       "User ID",
  updated:      "Updated",
  remove:       "Remove",
  noPush:       "No push subscriptions",
  confirmRemovePush: "Remove this push subscription?",
  pushRemoved:  "Subscription removed",

  broadcastSub:     "Send push notifications to users",
  sendNotif:        "📢 Send Notification",
  broadcastDesc:    "Send a push notification to trip members. Use for announcements, maintenance notices, or new feature alerts.",
  notifTitle:       "Notification Title (optional)",
  defaultTitle:     "Defaults to 'MateTrip'",
  message:          "Message *",
  messagePlaceholder: "Enter your message…",
  targetTrip:       "Target Trip",
  allTripsTarget:   "All trips",
  subscribers:      "subscriber(s) will receive this",
  sendBtn:          "📢 Send Notification",
  sending:          "Sending…",
  enterMessage:     "Enter a message",
  noSubscribers:    "No active subscribers found",
  sentSuccess:      "Sent to",
  devices:          "device(s)",
  tripsCount:       "trip(s)",

  tripInfo:     "Trip Info",
  tripIdLabel:  "Trip ID",
  joinCodeLabel:"Join Code",
  startDate:    "Start Date",
  endDate:      "End Date",
  totalMembers: "Total Members",
  totalSpend:   "Total Spend",
  activity:     "Activity Stats",
  schedule:     "Schedule",
  messages:     "Messages",
  photos:       "Photos",
  people:       "People",
  membersSection: "Members",
  deleteTrip:   "🗑 Delete Trip",
  confirmDeleteTrip: "Delete this trip and ALL its data?\nThis cannot be undone.",
  tripDeleted:  "Trip deleted",
  close:        "Close",
  loadingDetails: "Loading details…",

  accountInfo:  "Account Info",
  uid:          "UID",
  username:     "Username",
  displayName:  "Display Name",
  owned:        "Owned Trips",
  tripsLabel:   "Trips",
};

const LangContext = createContext(null);
export const useLang = () => useContext(LangContext);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("admin-lang") || "zh");
  const tr = lang === "zh" ? zh : en;
  const toggle = () => {
    const next = lang === "zh" ? "en" : "zh";
    setLang(next);
    localStorage.setItem("admin-lang", next);
  };
  return (
    <LangContext.Provider value={{ tr, lang, toggle }}>
      {children}
    </LangContext.Provider>
  );
}
