import { useLang } from '../../contexts/LangContext'

const mall_en = {
  storeName:          'JeeProd Mall',
  searchPlaceholder:  'Search products...',
  myOrders:           'My Orders',
  shopNow:            'Shop Now ↓',
  newArrivals:        '✨ NEW ARRIVALS',
  heroSub:            'Explore our curated collection. Quality products at fair prices.',
  all:                'All',
  allProducts:        'All Products',
  viewDetails:        'View Details',
  addToCart:          '🛒 Add to Cart',
  addedToCart:        '✓ Added!',
  backToShop:         '← Back to Shop',
  cart:               'Cart',
  cartEmpty:          'Your cart is empty.',
  startExploring:     'Start exploring products!',
  total:              'Total',
  checkout:           'Checkout →',
  placeOrder:         'Place Order',
  myOrdersTitle:      'My Orders',
  noOrders:           'No orders yet. Start shopping!',
  browseProducts:     'Browse Products →',
  orderDetails:       'Order Details',
  deliveryAddress:    'Delivery Address',
  notes:              'Notes',
  size:               'Size',
  designColor:        'Design / Color',
  quantity:           'Quantity',
  selectOne:          '— select one',
  aboutProduct:       'About this product',
  productNotFound:    'Product not found.',
  signInToView:       'Please sign in to view your orders.',
  loading:            'Loading...',
  noGearFound:        'No products found. Try a different filter.',
  items:              'items',
  item:               'item',
  results:            'Results for',
  name:               'Your Name',
  contactInfo:        'Contact Info',
  orderNotes:         'Notes (optional)',
  viaWhatsapp:        'via WhatsApp',
  viaEmail:           'via Email',
  yourName:           'Enter your name',
  yourContact:        'Phone / WhatsApp / Email',
  notesPlaceholder:   'Special instructions, etc.',
  sendOrder:          '🚀 Send Order',
  sending:            'Sending...',
  orderSuccess:       'Order Placed!',
  orderSuccessNote:   "We've received your order and will contact you shortly.",
  continueShop:       'Continue Shopping',
  orderRef:           'Order Reference',
  subtotal:           'Subtotal',
  orderItems:         'Order Items',
  contactMethod:      'Contact via',
}

const mall_zh = {
  storeName:          'JeeProd 商城',
  searchPlaceholder:  '搜索商品...',
  myOrders:           '我的订单',
  shopNow:            '立即购物 ↓',
  newArrivals:        '✨ 新品上架',
  heroSub:            '精选优质商品，价格公道实惠。',
  all:                '全部',
  allProducts:        '全部商品',
  viewDetails:        '查看详情',
  addToCart:          '🛒 加入购物车',
  addedToCart:        '✓ 已加入！',
  backToShop:         '← 返回商城',
  cart:               '购物车',
  cartEmpty:          '购物车是空的。',
  startExploring:     '去挑选喜欢的商品吧！',
  total:              '合计',
  checkout:           '去结算 →',
  placeOrder:         '提交订单',
  myOrdersTitle:      '我的订单',
  noOrders:           '暂无订单，快去购物吧！',
  browseProducts:     '浏览商品 →',
  orderDetails:       '订单详情',
  deliveryAddress:    '收货地址',
  notes:              '备注',
  size:               '尺寸',
  designColor:        '款式 / 颜色',
  quantity:           '数量',
  selectOne:          '— 请选择',
  aboutProduct:       '商品详情',
  productNotFound:    '商品不存在。',
  signInToView:       '请登录后查看您的订单。',
  loading:            '加载中...',
  noGearFound:        '没有找到相关商品，换个筛选条件试试。',
  items:              '件商品',
  item:               '件商品',
  results:            '搜索',
  name:               '您的姓名',
  contactInfo:        '联系方式',
  orderNotes:         '备注（可选）',
  viaWhatsapp:        '通过 WhatsApp',
  viaEmail:           '通过邮件',
  yourName:           '输入您的姓名',
  yourContact:        '电话 / WhatsApp / 邮箱',
  notesPlaceholder:   '特殊要求、备注等',
  sendOrder:          '🚀 提交订单',
  sending:            '提交中...',
  orderSuccess:       '订单已提交！',
  orderSuccessNote:   '我们已收到您的订单，将尽快与您联系。',
  continueShop:       '继续购物',
  orderRef:           '订单编号',
  subtotal:           '小计',
  orderItems:         '商品列表',
  contactMethod:      '联系方式',
}

export function useMallLang() {
  const { lang, toggleLang } = useLang()
  const m = lang === 'zh' ? mall_zh : mall_en
  const mt = (key) => m[key] ?? key
  return { lang, toggleLang, mt }
}
